name: csci2952X
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - absl-py=2.1.0
  - antlr4-python3-runtime=4.9.3
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - arrow=1.3.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - brotli=1.0.9
  - c-ares=1.19.1
  - cairo=1.16.0
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cuda-cudart=12.4.127
  - cuda-libraries=12.4.1
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - dill=0.3.8
  - eigen=3.4.0
  - fonttools=4.51.0
  - grpcio=1.62.2
  - hdf5=1.12.1
  - ipykernel=6.29.5
  - jinja2=3.1.4
  - jupyterlab=4.2.5
  - kiwisolver=1.4.4
  - libtiff=4.5.1
  - matplotlib=3.9.2
  - tqdm=4.66.5

